name: Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target
      
  #    - run: mkdir staging && mv target/yb-workload-sim.jar target/yb-workload-sim-${{ env.build-number }}.jar && cp target/*.jar staging
   #       retention-days: 1
   #   - uses: marvinpinto/action-automatic-releases@latest
   #     with:
   #       repo_token: "${{ secrets.YOUR-GITHUB-TOKEN }}"
   #       automatic_release_tag: "${{ github.run_number }}"
   #       title: "Automated Build ${{ github.run_number }}"
   #       prerelease: true
   #       files: staging/*.jar
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maxkrivenya/pnajava:latest
